# Generated by Django 2.2.1 on 2019-06-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20190602_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.TextField(default='', max_length=128),
        ),
    ]
