# Generated by Django 2.2.3 on 2019-07-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_list_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('text', 'list')},
        ),
    ]
